// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AiMlDocumentDataSlicesSlice = never;

/**
 * Item in *AI/ML → AI/Ml Steps*
 */
export interface AiMlDocumentDataAiStepsItem {
  /**
   * Title field in *AI/ML → AI/Ml Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_steps[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Icon field in *AI/ML → AI/Ml Steps*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_steps[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Description field in *AI/ML → AI/Ml Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_steps[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *AI/ML → AI/ML Signs*
 */
export interface AiMlDocumentDataAiSignsItem {
  /**
   * Title field in *AI/ML → AI/ML Signs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_signs[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *AI/ML → AI/ML Signs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_signs[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Icon field in *AI/ML → AI/ML Signs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_signs[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Item in *AI/ML → Benefits*
 */
export interface AiMlDocumentDataBenefitsItem {
  /**
   * Title field in *AI/ML → Benefits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.benefits[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *AI/ML → Benefits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.benefits[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Icon field in *AI/ML → Benefits*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.benefits[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Item in *AI/ML → Examples*
 */
export interface AiMlDocumentDataExamplesItem {
  /**
   * Title field in *AI/ML → Examples*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.examples[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *AI/ML → Examples*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.examples[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *AI/ML → Examples*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.examples[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *AI/ML → Content*
 */
export interface AiMlDocumentDataWhyUsListItem {
  /**
   * Title field in *AI/ML → Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.why_us_list[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *AI/ML → Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.why_us_list[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Content for AI/ML documents
 */
interface AiMlDocumentData {
  /**
   * Hero Video field in *AI/ML*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.hero_video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_video: prismic.LinkToMediaField;

  /**
   * Slice Zone field in *AI/ML*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AiMlDocumentDataSlicesSlice> /**
   * Meta Title field in *AI/ML*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: ai_ml.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *AI/ML*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: ai_ml.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField /**
   * Data Science field in *AI/ML*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.data_science
   * - **Tab**: AI/ML
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  data_science: prismic.KeyTextField /**
   * What Is AI field in *AI/ML*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.what_is_ai
   * - **Tab**: What is AI/ML
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  what_is_ai: prismic.KeyTextField /**
   * AI/Ml Steps field in *AI/ML*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_steps[]
   * - **Tab**: Steps
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  ai_steps: prismic.GroupField<Simplify<AiMlDocumentDataAiStepsItem>> /**
   * AI/ML Signs field in *AI/ML*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_signs[]
   * - **Tab**: Signs
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  ai_signs: prismic.GroupField<Simplify<AiMlDocumentDataAiSignsItem>> /**
   * Benefits field in *AI/ML*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.benefits[]
   * - **Tab**: Benefits
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  benefits: prismic.GroupField<Simplify<AiMlDocumentDataBenefitsItem>> /**
   * Examples field in *AI/ML*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.examples[]
   * - **Tab**: Examples
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  examples: prismic.GroupField<Simplify<AiMlDocumentDataExamplesItem>> /**
   * Image field in *AI/ML*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.why_us_image
   * - **Tab**: Why Us
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  why_us_image: prismic.ImageField<never>;

  /**
   * Content field in *AI/ML*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.why_us_list[]
   * - **Tab**: Why Us
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  why_us_list: prismic.GroupField<Simplify<AiMlDocumentDataWhyUsListItem>>;
}

/**
 * AI/ML document from Prismic
 *
 * - **API ID**: `ai_ml`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AiMlDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AiMlDocumentData>, "ai_ml", Lang>;

type HomeDocumentDataSlicesSlice = never;

/**
 * Item in *Home → Questions*
 */
export interface HomeDocumentDataQuestionsItem {
  /**
   * Title field in *Home → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.questions[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Answer field in *Home → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.questions[].answer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer: prismic.KeyTextField;
}

/**
 * Item in *Home → Expertise*
 */
export interface HomeDocumentDataExpertiseItem {
  /**
   * Title field in *Home → Expertise*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.expertise[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Info field in *Home → Expertise*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.expertise[].info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;

  /**
   * Icon field in *Home → Expertise*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.expertise[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Url field in *Home → Expertise*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.expertise[].url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField;
}

/**
 * Item in *Home → Engagement*
 */
export interface HomeDocumentDataEngagementItem {
  /**
   * Title field in *Home → Engagement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.engagement[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Info field in *Home → Engagement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.engagement[].info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;

  /**
   * Image field in *Home → Engagement*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.engagement[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Home → Case Studies*
 */
export interface HomeDocumentDataCaseStudiesItem {
  /**
   * Title field in *Home → Case Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.case_studies[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slug field in *Home → Case Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.case_studies[].slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Info field in *Home → Case Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.case_studies[].info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;

  /**
   * Image field in *Home → Case Studies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.case_studies[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *Home → Case Studies*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.case_studies[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Item in *Home → Why Cards*
 */
export interface HomeDocumentDataWhyCardsItem {
  /**
   * Icon field in *Home → Why Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.why_cards[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Content field in *Home → Why Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.why_cards[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Hero Video field in *Home*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_video: prismic.LinkToMediaField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField /**
   * Questions field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.questions[]
   * - **Tab**: Banner
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  questions: prismic.GroupField<Simplify<HomeDocumentDataQuestionsItem>> /**
   * Expertise field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.expertise[]
   * - **Tab**: Expertise
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  expertise: prismic.GroupField<Simplify<HomeDocumentDataExpertiseItem>> /**
   * Engagement field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.engagement[]
   * - **Tab**: Engagement
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  engagement: prismic.GroupField<Simplify<HomeDocumentDataEngagementItem>> /**
   * Case Studies field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.case_studies[]
   * - **Tab**: Case Studies
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  case_studies: prismic.GroupField<
    Simplify<HomeDocumentDataCaseStudiesItem>
  > /**
   * About Content field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_content
   * - **Tab**: About Us
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  about_content: prismic.RichTextField;

  /**
   * Why Cards field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.why_cards[]
   * - **Tab**: About Us
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  why_cards: prismic.GroupField<Simplify<HomeDocumentDataWhyCardsItem>>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | CtaSlice
  | TextWithImageSlice
  | TitleWithAnalyticsSlice
  | TitleWithTextSlice
  | TitleWithCardCarouselSlice
  | TitleWithStepsSlice
  | TitleWithExpertiseSlice
  | TitleWithButtonSlice
  | TitleWithCardsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = AiMlDocument | HomeDocument | PageDocument;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Heading field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Text field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Button field in *CallToAction → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Primary content in *TextWithImage → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
  /**
   * Title field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Image field in *TextWithImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *TextWithImage → Items*
 */
export interface TextWithImageSliceDefaultItem {
  /**
   * Title field in *TextWithImage → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *TextWithImage → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for TextWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithImageSliceDefaultPrimary>,
  Simplify<TextWithImageSliceDefaultItem>
>;

/**
 * Slice variation for *TextWithImage*
 */
type TextWithImageSliceVariation = TextWithImageSliceDefault;

/**
 * TextWithImage Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSlice = prismic.SharedSlice<
  "text_with_image",
  TextWithImageSliceVariation
>;

/**
 * Primary content in *Features → Primary*
 */
export interface TitleWithAnalyticsSliceDefaultPrimary {
  /**
   * Title field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_analytics.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Features → Items*
 */
export interface TitleWithAnalyticsSliceDefaultItem {
  /**
   * Icon field in *Features → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_analytics.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_analytics.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_analytics.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithAnalyticsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleWithAnalyticsSliceDefaultPrimary>,
  Simplify<TitleWithAnalyticsSliceDefaultItem>
>;

/**
 * Primary content in *Features → Primary*
 */
export interface TitleWithAnalyticsSliceSecondaryPrimary {
  /**
   * Title field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_analytics.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Features → Items*
 */
export interface TitleWithAnalyticsSliceSecondaryItem {
  /**
   * Icon field in *Features → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_analytics.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_analytics.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_analytics.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Secondary variation for Features Slice
 *
 * - **API ID**: `secondary`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithAnalyticsSliceSecondary = prismic.SharedSliceVariation<
  "secondary",
  Simplify<TitleWithAnalyticsSliceSecondaryPrimary>,
  Simplify<TitleWithAnalyticsSliceSecondaryItem>
>;

/**
 * Primary content in *Features → Primary*
 */
export interface TitleWithAnalyticsSliceThirdPrimary {
  /**
   * Title field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_analytics.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Features → Items*
 */
export interface TitleWithAnalyticsSliceThirdItem {
  /**
   * Icon field in *Features → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_analytics.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_analytics.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_analytics.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Third variation for Features Slice
 *
 * - **API ID**: `third`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithAnalyticsSliceThird = prismic.SharedSliceVariation<
  "third",
  Simplify<TitleWithAnalyticsSliceThirdPrimary>,
  Simplify<TitleWithAnalyticsSliceThirdItem>
>;

/**
 * Slice variation for *Features*
 */
type TitleWithAnalyticsSliceVariation =
  | TitleWithAnalyticsSliceDefault
  | TitleWithAnalyticsSliceSecondary
  | TitleWithAnalyticsSliceThird;

/**
 * Features Shared Slice
 *
 * - **API ID**: `title_with_analytics`
 * - **Description**: TitleWithAnalytics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithAnalyticsSlice = prismic.SharedSlice<
  "title_with_analytics",
  TitleWithAnalyticsSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface TitleWithButtonSliceDefaultPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_button.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Button field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_button.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField;

  /**
   * Video field in *Hero → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_button.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleWithButtonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type TitleWithButtonSliceVariation = TitleWithButtonSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `title_with_button`
 * - **Description**: TitleWithButton
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithButtonSlice = prismic.SharedSlice<
  "title_with_button",
  TitleWithButtonSliceVariation
>;

/**
 * Primary content in *Carousel → Primary*
 */
export interface TitleWithCardCarouselSliceDefaultPrimary {
  /**
   * Title field in *Carousel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_card_carousel.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Carousel → Items*
 */
export interface TitleWithCardCarouselSliceDefaultItem {
  /**
   * Image field in *Carousel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_card_carousel.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Carousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_card_carousel.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Carousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_card_carousel.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithCardCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleWithCardCarouselSliceDefaultPrimary>,
  Simplify<TitleWithCardCarouselSliceDefaultItem>
>;

/**
 * Slice variation for *Carousel*
 */
type TitleWithCardCarouselSliceVariation = TitleWithCardCarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `title_with_card_carousel`
 * - **Description**: TitleWithCardCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithCardCarouselSlice = prismic.SharedSlice<
  "title_with_card_carousel",
  TitleWithCardCarouselSliceVariation
>;

/**
 * Primary content in *Cards → Primary*
 */
export interface TitleWithCardsSliceDefaultPrimary {
  /**
   * Title field in *Cards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_cards.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Cards → Items*
 */
export interface TitleWithCardsSliceDefaultItem {
  /**
   * Image field in *Cards → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Cards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Cards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_cards.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleWithCardsSliceDefaultPrimary>,
  Simplify<TitleWithCardsSliceDefaultItem>
>;

/**
 * Slice variation for *Cards*
 */
type TitleWithCardsSliceVariation = TitleWithCardsSliceDefault;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `title_with_cards`
 * - **Description**: TitleWithCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithCardsSlice = prismic.SharedSlice<
  "title_with_cards",
  TitleWithCardsSliceVariation
>;

/**
 * Primary content in *Expertise → Primary*
 */
export interface TitleWithExpertiseSliceDefaultPrimary {
  /**
   * Title field in *Expertise → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_expertise.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Expertise → Items*
 */
export interface TitleWithExpertiseSliceDefaultItem {
  /**
   * Url field in *Expertise → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_expertise.items[].url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField;

  /**
   * Icon field in *Expertise → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_expertise.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Expertise → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_expertise.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Expertise → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_expertise.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Expertise Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithExpertiseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleWithExpertiseSliceDefaultPrimary>,
  Simplify<TitleWithExpertiseSliceDefaultItem>
>;

/**
 * Slice variation for *Expertise*
 */
type TitleWithExpertiseSliceVariation = TitleWithExpertiseSliceDefault;

/**
 * Expertise Shared Slice
 *
 * - **API ID**: `title_with_expertise`
 * - **Description**: TitleWithExpertise
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithExpertiseSlice = prismic.SharedSlice<
  "title_with_expertise",
  TitleWithExpertiseSliceVariation
>;

/**
 * Primary content in *Steps → Primary*
 */
export interface TitleWithStepsSliceDefaultPrimary {
  /**
   * Title field in *Steps → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_steps.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Steps → Items*
 */
export interface TitleWithStepsSliceDefaultItem {
  /**
   * Icon field in *Steps → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_steps.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Steps → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_steps.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Steps → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_steps.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Steps Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithStepsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleWithStepsSliceDefaultPrimary>,
  Simplify<TitleWithStepsSliceDefaultItem>
>;

/**
 * Slice variation for *Steps*
 */
type TitleWithStepsSliceVariation = TitleWithStepsSliceDefault;

/**
 * Steps Shared Slice
 *
 * - **API ID**: `title_with_steps`
 * - **Description**: TitleWithSteps
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithStepsSlice = prismic.SharedSlice<
  "title_with_steps",
  TitleWithStepsSliceVariation
>;

/**
 * Primary content in *TitleWithText → Primary*
 */
export interface TitleWithTextSliceDefaultPrimary {
  /**
   * Title field in *TitleWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *TitleWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * textColor field in *TitleWithText → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.primary.textcolor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  textcolor: prismic.ColorField;
}

/**
 * Default variation for TitleWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TitleWithText*
 */
type TitleWithTextSliceVariation = TitleWithTextSliceDefault;

/**
 * TitleWithText Shared Slice
 *
 * - **API ID**: `title_with_text`
 * - **Description**: TitleWithText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithTextSlice = prismic.SharedSlice<
  "title_with_text",
  TitleWithTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AiMlDocument,
      AiMlDocumentData,
      AiMlDocumentDataSlicesSlice,
      AiMlDocumentDataAiStepsItem,
      AiMlDocumentDataAiSignsItem,
      AiMlDocumentDataBenefitsItem,
      AiMlDocumentDataExamplesItem,
      AiMlDocumentDataWhyUsListItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      HomeDocumentDataQuestionsItem,
      HomeDocumentDataExpertiseItem,
      HomeDocumentDataEngagementItem,
      HomeDocumentDataCaseStudiesItem,
      HomeDocumentDataWhyCardsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      TextWithImageSlice,
      TextWithImageSliceDefaultPrimary,
      TextWithImageSliceDefaultItem,
      TextWithImageSliceVariation,
      TextWithImageSliceDefault,
      TitleWithAnalyticsSlice,
      TitleWithAnalyticsSliceDefaultPrimary,
      TitleWithAnalyticsSliceDefaultItem,
      TitleWithAnalyticsSliceSecondaryPrimary,
      TitleWithAnalyticsSliceSecondaryItem,
      TitleWithAnalyticsSliceThirdPrimary,
      TitleWithAnalyticsSliceThirdItem,
      TitleWithAnalyticsSliceVariation,
      TitleWithAnalyticsSliceDefault,
      TitleWithAnalyticsSliceSecondary,
      TitleWithAnalyticsSliceThird,
      TitleWithButtonSlice,
      TitleWithButtonSliceDefaultPrimary,
      TitleWithButtonSliceVariation,
      TitleWithButtonSliceDefault,
      TitleWithCardCarouselSlice,
      TitleWithCardCarouselSliceDefaultPrimary,
      TitleWithCardCarouselSliceDefaultItem,
      TitleWithCardCarouselSliceVariation,
      TitleWithCardCarouselSliceDefault,
      TitleWithCardsSlice,
      TitleWithCardsSliceDefaultPrimary,
      TitleWithCardsSliceDefaultItem,
      TitleWithCardsSliceVariation,
      TitleWithCardsSliceDefault,
      TitleWithExpertiseSlice,
      TitleWithExpertiseSliceDefaultPrimary,
      TitleWithExpertiseSliceDefaultItem,
      TitleWithExpertiseSliceVariation,
      TitleWithExpertiseSliceDefault,
      TitleWithStepsSlice,
      TitleWithStepsSliceDefaultPrimary,
      TitleWithStepsSliceDefaultItem,
      TitleWithStepsSliceVariation,
      TitleWithStepsSliceDefault,
      TitleWithTextSlice,
      TitleWithTextSliceDefaultPrimary,
      TitleWithTextSliceVariation,
      TitleWithTextSliceDefault,
    };
  }
}
