// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta: dynamic(() => import("./CallToAction")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  title_with_analytics: dynamic(() => import("./Features")),
  title_with_button: dynamic(() => import("./Hero")),
  title_with_card_carousel: dynamic(() => import("./Carousel")),
  title_with_cards: dynamic(() => import("./Cards")),
  title_with_expertise: dynamic(() => import("./Expertise")),
  title_with_steps: dynamic(() => import("./Steps")),
  title_with_text: dynamic(() => import("./TitleWithText")),
};
